version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --requirepass your_redis_password_here
    volumes:
      - .database/redis_data:/data


volumes:
  redis_data:


# docker run --name mongo -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME="dipghosh" -e MONGO_INITDB_ROOT_PASSWORD="yesthisispassword" -d prismagraphql/mongo-single-replica:5.0.3