services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --requirepass your_redis_password_here
    volumes:
      - .database/redis_data:/data
  

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .database/data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic


  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .database/data02:/usr/share/elasticsearch/data
    networks:
      - elastic



  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .database/data03:/usr/share/elasticsearch/data
    networks:
      - elastic


volumes:
  redis_data:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge

# docker run --name mongo -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME="dipghosh" -e MONGO_INITDB_ROOT_PASSWORD="yesthisispassword" -d prismagraphql/mongo-single-replica:5.0.3